version: '3.8'

services:
  storage:
    image: postgres:15.3
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
    - 5432:5432
    volumes:
    - data:/var/lib/postgresql/data
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  metabase:
    image: metabase/metabase:latest
    restart: always
    expose:
      - 3000
    ports:
      - 3000:3000

volumes:
  data:
    driver: local
