/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tglanz;

import static org.junit.Assert.assertNotEquals;

import java.io.IOException;

import org.junit.Test;

import tglanz.examples.ExamplesLoader;

public class AppTest {
    @Test public void exampleLoaderReturnExamples() throws IOException {
//        var loader = new ExamplesLoader();
//        var examples = loader.loadExamples();
//        assertNotEquals(examples.size(), 0);
    }
}
